version: '3.6'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "monolith"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
