version: '3.6'

services:
  product-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "product"
    volumes:
      - product-db-data:/var/lib/postgresql/data

  product:
    image: node:alpine
    volumes:
      - ./product:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://root:password@product-db:5432/product
      - PORT=3000
      - JWT_SECRET=s3cr3t
      - NODE_ENV=dev
    command: "sh -c 'npm install; npm run start'"

volumes:
  db-data: {}
