version: '3.6'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "product"
    volumes:
      - db-data:/var/lib/postgresql/data

  product:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://root:password@db:5432/product
      - PORT=3000
      - JWT_SECRET=s3cr3t
      - NODE_ENV=dev
    ports:
      - "3000:3000"
    command: "sh -c 'npm install; npm run start'"

volumes:
  db-data: {}
