name: GitHub Actions CI
on: [push]
jobs:
  check-changed-services:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/microservices
      - name: Build docker-compose
        run: docker-compose -f ./microservices/authentication/docker-compose.yml up -d
      - name: NPM Install
        run: |
          docker exec authentication_authentication_1 npm install
      - name: Run tests if git diff
        run: |
          CHANGED=$(git diff --quiet HEAD master -- microservices | echo changed)
          if [[ $CHANGED ]]; then
              docker exec authentication_authentication_1 npm test
          else
              echo 'No changes to authentication service'
          fi
