name: GitHub Actions CI
on: [push]
jobs:
  check-changed-services:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/microservices
      - name: Run tests if git diff
        run: |
          if [ git diff --quiet HEAD master -- microservices | echo changed ]; then
            docker-compose -f ${{ github.workspace }}/microservices/authentication/docker-compose.yml run authentication npm test -d --build
          else
            echo 'No changes to authentication service'
          fi
